using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net.Sockets;
using System.Net;
using System.Threading;
using Utility;
using System.Runtime.CompilerServices;
using System.Net.NetworkInformation;
using System.Net.Configuration;
using System.Runtime.InteropServices;

namespace ChatServer
{
	class Program
	{
		private static Dictionary<Guid, List<TcpClient>> RoomClients = new Dictionary<Guid, List<TcpClient>>();
		private static List<TcpClient> ConnectedClients = new List<TcpClient>();

		static async Task Main (string[] args)
		{
			// "All threads generated by creating and starting a new Thread object are by default foreground threads."
			var serverBroadcastThread = new Thread(new ThreadStart( () => {
				UdpClient server = new UdpClient(11000);
				
				while (true)
				{
					var clientEp = new IPEndPoint(IPAddress.Any, 0);
					server.Receive(ref clientEp);
					
					var adress = Encoding.ASCII.GetBytes(Utility.Utility.GetLocalIPAddress());
					server.Send(adress, adress.Length, clientEp);
				}	
			}));

			serverBroadcastThread.IsBackground = true;
			serverBroadcastThread.Start();

			TcpListener serverSocket = new TcpListener(IPAddress.Any, 7777);
			
			serverSocket.Start();
			Console.WriteLine(" >> Server Started");

			Task<TcpClient> client = null;
			while (true)
			{
				if (client == null )
				{
					client = serverSocket.AcceptTcpClientAsync();
				}
				if (client.IsCompleted)
				{
					ConnectedClients.Add(client.Result);
					Console.WriteLine(" >> Client connected!");

					client = null;
				}

				foreach (var connectedClient in ConnectedClients)
				{
					NetworkStream ns = connectedClient.GetStream();
					
					if (ns.DataAvailable)
					{
						byte[] data = new byte[1024];

						int count = await ns.ReadAsync(data, 0, data.Length);
						var payload = Encoding.ASCII.GetString(data, 0, count).Split(';');
						
						switch(payload[0])
						{
							case "leave":
								var leaver = new KeyValuePair<Guid, TcpClient>(Guid.Parse(payload[1]), connectedClient);
								RoomClients[leaver.Key].Remove(leaver.Value);
								LeaveRoom(connectedClient, payload[1]);
								break;
							case "leaveAll":
								LeaveAll(connectedClient);
								break;
							case "post":
								PostMessage(payload, connectedClient);
								break;
							case "join":
								RoomClients[Guid.Parse(payload[1])].Add(connectedClient);
								break;
							case "refresh":
								RefreshRooms(connectedClient);
								break;
							case "newroom":
								NewRoom(connectedClient);
								break;
							default:
								Console.WriteLine("default");
								break;
						}
					}
				}
			}
		}

		private static async void NewRoom (TcpClient client)
		{
			NetworkStream ns = client.GetStream();

			Guid roomId = Guid.NewGuid();
			RoomClients[roomId] = new List<TcpClient>(){client};

			string response = "newroom;" + roomId.ToString();

			await ns.WriteAsync(Encoding.ASCII.GetBytes(response), 0, response.Length);
		}

		private static async void LeaveRoom (TcpClient client, string roomId)
		{
			NetworkStream ns = client.GetStream();

			string response = "leave;" + roomId;

			await ns.WriteAsync(Encoding.ASCII.GetBytes(response), 0, response.Length);
		}

		private static void LeaveAll (TcpClient client)
		{
			foreach (var room in RoomClients)
			{
				if (room.Value.Contains(client))
				{
					room.Value.Remove(client);				
				}
			}
		}

		private static async void PostMessage (string[] payload, TcpClient sender)
		{
			string data;
			byte[] message;

			foreach (TcpClient c in RoomClients[Guid.Parse(payload[1])])
			{
				string sameClient = c == sender ? ";1" : ";0";

				data = payload[0] + ';' + payload[1] + ';' + payload[2] + sameClient + ';' + payload[3];

				message = Encoding.ASCII.GetBytes(data);

				NetworkStream clientNs = c.GetStream();

				await clientNs.WriteAsync(message, 0, message.Length);	
			}
		}

		private static async void RefreshRooms (TcpClient client)
		{
			NetworkStream ns = client.GetStream();
			string stringifiedChatRooms = "refresh;None";
			
			if (RoomClients.Count > 0)
			{
				stringifiedChatRooms = "refresh";
				for (int i = 0; i < RoomClients.Count; i++)
				{
					string roomId = RoomClients.Keys.ToList()[i].ToString();
					string numOfParticipants = RoomClients[Guid.Parse(roomId)].Count.ToString();

					stringifiedChatRooms += ";Room " + i.ToString() + '|' + roomId + '|' + numOfParticipants;
				}			
			}
			
			await ns.WriteAsync(Encoding.ASCII.GetBytes(stringifiedChatRooms), 0, stringifiedChatRooms.Length);	
		}
	}
}
